// ============================================================
// CODEMACHAN — THE FRIENDLY SOFTWARE STUDIO DATA & CONTENT SYSTEM
// ============================================================

export const PROFILE = {
  brandName: "CODEMACHAN",
  studioTitle: "The Friendly Software Studio",
  name: "Aravind",
  firstName: "Aravind",
  role: "Lead Software Architect & Student Builder",
  
  // Hero headlines
  headline: "Got an idea?",
  secondaryHeadline: "Let's build the thing.",
  supportingText: "Websites, apps, student projects and crazy ideas — we turn them into something that actually works.",
  playfulSubtext: "Yes, even that idea you have in your Notes app.",
  
  // Live Status Indicator (driven by DB/Admin)
  availability: "available" as "available" | "busy" | "unavailable",
  availabilityStatus: "● Currently building stuff",
  availabilityText: "Online & taking new projects",
  
  // Student & Persona Details
  education: "3rd Year Computer Science & Engineering",
  course: "B.Tech Computer Science",
  yearOfStudy: "3rd Year CS Student",
  institution: "College of Engineering",
  location: "India (Serving Students & Creators Globally)",
  
  // Profile details for "Who's behind CodeMachan?"
  currently: "Building useful digital products",
  usuallyFound: "VS Code + Chrome + Coffee",
  currentObsession: "Making websites less boring",
  
  loves: [
    "You bring the idea. We figure out the code.",
    "Clean UI that doesn't hurt your eyes",
    "Shipping before the deadline panic begins",
    "Building things people actually use",
  ],
  hates: [
    "Corporate jargon & bloated templates",
    "UI that looks like a 2004 government portal",
    "Over-engineered setups that break at 3 AM",
  ],
  
  bio: "CodeMachan is a software development studio focused on turning ideas into useful digital products. Founded by Aravind, a 3rd-year CS student, we combine modern software engineering precision with a fresh, creative student brand identity.",
  bioExtended: "Whether your submission deadline is next week, you're launching a campus startup, or you're finally building that product concept in your head — we handle design, backend architecture, and seamless cloud deployment.",
  
  email: "codemachan@gmail.com",
  phone: "+91 98765 43210",
  githubUrl: "https://github.com/yourusername",
  linkedinUrl: "https://linkedin.com/in/yourusername",
  twitterUrl: "https://twitter.com/codemachan",
  instagramUrl: "https://instagram.com/codemachan",
  websiteUrl: "https://codemachan.vercel.app",
};

// Section 2: "Okay, so... what is CodeMachan?"
export const WHAT_IS_CODEMACHAN_ITEMS = [
  {
    id: "websites",
    title: "Websites",
    punchline: "Fast, sleek, custom-designed sites that turn visitors into fans.",
    iconName: "Globe",
    emoji: "🌐",
  },
  {
    id: "web-apps",
    title: "Web Applications",
    punchline: "Full-stack apps with user login, databases, and custom logic.",
    iconName: "Layers",
    emoji: "📱",
  },
  {
    id: "student-projects",
    title: "Student Projects",
    punchline: "Academic capstones and coursework built with top-tier code & docs.",
    iconName: "GraduationCap",
    emoji: "🎓",
  },
  {
    id: "saas",
    title: "SaaS Products",
    punchline: "Lightweight MVPs to validate your idea and start onboarding users.",
    iconName: "Rocket",
    emoji: "🚀",
  },
  {
    id: "apis",
    title: "APIs & Databases",
    punchline: "Solid backend architecture, PostgreSQL models, and REST endpoints.",
    iconName: "Server",
    emoji: "⚙️",
  },
  {
    id: "custom-software",
    title: "Custom Software",
    punchline: "AI helpers, automation scripts, and custom tools built to spec.",
    iconName: "Cpu",
    emoji: "🛠️",
  },
];

// Section 3: "What can we build?"
export const SERVICES = [
  {
    id: "1",
    slug: "website-development",
    icon: "Globe",
    emoji: "🌐",
    title: "Website Development",
    tagline: "Something better than a template.",
    shortDescription: "Custom websites engineered for speed, clean typography, dark mode aesthetics, and flawless mobile responsiveness.",
    description: "Designed from scratch with Next.js and Tailwind CSS. Zero bloated WordPress templates, sub-second page loads, SEO optimization, and custom domain setup.",
    deliverables: [
      "Custom responsive interface (Mobile + Desktop)",
      "Sub-second page load performance",
      "SEO & social share card configuration",
      "Contact form with instant email alerts",
      "One-click deployment to Vercel",
    ],
    color: "#a855f7",
    accentGlow: "rgba(168, 85, 247, 0.15)",
  },
  {
    id: "2",
    slug: "web-applications",
    icon: "Layers",
    emoji: "📱",
    title: "Web Applications",
    tagline: "An actual product, not just a pretty homepage.",
    shortDescription: "Complete full-stack applications with secure user authentication, relational databases, admin panels, and API logic.",
    description: "Built on Next.js, Supabase, and PostgreSQL. We implement row-level security, auth flows (Google, Magic Link, Email), file storage, and scalable backend edge functions.",
    deliverables: [
      "User authentication & permissions",
      "PostgreSQL database schema & RLS security",
      "Interactive dashboard & CRUD workflows",
      "File uploads & media storage",
      "Automated backend edge functions",
    ],
    color: "#ec4899",
    accentGlow: "rgba(236, 72, 153, 0.15)",
  },
  {
    id: "3",
    slug: "student-projects",
    icon: "GraduationCap",
    emoji: "🎓",
    title: "Student Projects",
    tagline: "Because deadlines have no mercy.",
    shortDescription: "Complete academic capstone projects with working source code, IEEE-format documentation, presentation slides, and viva prep.",
    description: "Turn your project concept into an impressive final-year submission. Includes commented source code, full project report PDF, PPT slides, and a 1-on-1 walkthrough so you ace your viva.",
    deliverables: [
      "Clean, heavily commented source code",
      "Comprehensive project documentation (Word/PDF)",
      "Presentation slides (PPT) & ER diagrams",
      "Setup & execution guide (README)",
      "1-on-1 code walkthrough session for viva",
    ],
    color: "#38bdf8",
    accentGlow: "rgba(56, 189, 248, 0.15)",
  },
  {
    id: "4",
    slug: "portfolio-websites",
    icon: "User",
    emoji: "🎨",
    title: "Portfolio Websites",
    tagline: "Make your work look as good as your work actually is.",
    shortDescription: "Standout creative portfolios that highlight your projects, skills, and unique brand identity to recruiters and clients.",
    description: "Custom interactive developer and creator portfolios. Say goodbye to cookie-cutter resume themes and stand out with interactive case studies and smooth transitions.",
    deliverables: [
      "Custom visual identity & signature layout",
      "Interactive project showcases & case studies",
      "Filterable skills & work experience",
      "Direct inquiry & booking form",
      "Full GitHub repository handover",
    ],
    color: "#10b981",
    accentGlow: "rgba(16, 185, 129, 0.15)",
  },
  {
    id: "5",
    slug: "mvp-development",
    icon: "Rocket",
    emoji: "🚀",
    title: "MVP Development",
    tagline: "Got an idea? Let's get it out of your head and onto the internet.",
    shortDescription: "Rapid turnaround v1 products for student founders and creators ready to launch, test user demand, and pitch.",
    description: "Streamlined MVP development built to validate your core product hypothesis fast. Skip unnecessary features and launch a working product in weeks.",
    deliverables: [
      "Core feature build focused on user retention",
      "Payment gateway integration (Stripe / Razorpay)",
      "User onboarding & analytics setup",
      "Production deployment to Vercel/Supabase",
      "14 days post-launch technical support",
    ],
    color: "#f59e0b",
    accentGlow: "rgba(245, 158, 11, 0.15)",
  },
  {
    id: "6",
    slug: "backend-apis",
    icon: "Server",
    emoji: "⚙️",
    title: "Backend & APIs",
    tagline: "The stuff users don't see, but everything depends on.",
    shortDescription: "Fast, reliable REST APIs, database models, authentication setups, and cloud integrations for modern web apps.",
    description: "Database design, row-level security policies, serverless edge functions, third-party API sync, and rate limiting middleware for production web apps.",
    deliverables: [
      "PostgreSQL schema design & optimization",
      "Row-Level Security (RLS) policies",
      "RESTful API endpoints with validation",
      "Webhook pipelines & third-party service sync",
      "Postman API documentation",
    ],
    color: "#c084fc",
    accentGlow: "rgba(192, 132, 252, 0.15)",
  },
];

// Section 4: "College life has enough problems."
export const STUDENT_PROBLEMS = [
  {
    id: "1",
    title: "Final year project due next week?",
    subtitle: "And your group is still arguing in WhatsApp about who handles the frontend.",
    solution: "Rapid sprint build: complete working app + documentation + PPT slides ready for evaluation.",
    emoji: "⏳",
    tag: "Urgent Deadline",
  },
  {
    id: "2",
    title: "I have an idea but don't know where to start.",
    subtitle: "You have a great concept in your Notes app but no clue how to build the database or UI.",
    solution: "We turn your rough notes into a clear tech architecture and build the working v1.",
    emoji: "💡",
    tag: "Concept to Code",
  },
  {
    id: "3",
    title: "My project works on my laptop...",
    subtitle: "CORS errors, environment secret leaks, and mysterious crashes whenever someone else opens it.",
    solution: "Clean refactoring into Next.js + Supabase deployed to Vercel with zero runtime surprises.",
    emoji: "🐛",
    tag: "Fix & Deploy",
  },
  {
    id: "4",
    title: "My UI looks terrible.",
    subtitle: "The backend logic works, but the frontend looks like a 2003 government form.",
    solution: "Complete visual redesign with modern dark mode, clean typography, and smooth micro-interactions.",
    emoji: "🏛️",
    tag: "Visual Upgrade",
  },
  {
    id: "5",
    title: "I need to explain this thing in my viva.",
    subtitle: "Terrified the examiner will ask \"what does line 142 in auth.ts actually do?\"",
    solution: "Includes a 1-on-1 video call code walkthrough so you can explain every single line with confidence.",
    emoji: "🗣️",
    tag: "Viva Defense",
  },
  {
    id: "6",
    title: "I need a website.",
    subtitle: "For your personal brand, club event, portfolio, or local business that needs to look fire.",
    solution: "Custom-designed modern website built with sub-second page load speed and dark mode.",
    emoji: "🌐",
    tag: "Custom Site",
  },
  {
    id: "7",
    title: "I need to turn my idea into an actual product.",
    subtitle: "Ready to launch a real web app with users, authentication, and database features.",
    solution: "Full-stack MVP development built on production-grade Next.js and Supabase.",
    emoji: "🚀",
    tag: "Full MVP",
  },
];

// Section 5: "Things we've built."
export const PROJECTS = [
  {
    id: "1",
    slug: "codemachan-platform",
    title: "CodeMachan Studio Platform",
    tagline: "The friendly software studio website for students & creators",
    shortDescription: "An interactive, modern studio website featuring a floating digital workspace, outcome-focused service showcases, student problem solver, and case studies.",
    description: "A production-grade web platform designed to demonstrate modern software studio craftsmanship. Combines clean dark mode visuals, student problem solver cards, and an interactive contact flow.",
    problem: "Generic developer portfolios alienate students and creators with corporate jargon, dull resume layouts, and tech pill overload.",
    solution: "Engineered a friendly software studio brand with outcome-driven services, responsive digital workspace graphics, and transparent communication.",
    results: "3x higher user engagement time, instant brand clarity, and 100% student-focused user experience.",
    category: "Full Stack",
    status: "completed",
    tech: ["Next.js 15", "TypeScript", "Tailwind CSS", "Supabase", "Framer Motion"],
    keyFeatures: [
      "Interactive floating digital workspace",
      "Outcome-driven service showcase",
      "Student problem diagnosis matrix",
      "Full case study viewer & project gallery",
      "Responsive across all devices",
    ],
    githubUrl: "https://github.com/yourusername/codemachan",
    liveUrl: "https://codemachan.vercel.app",
    featured: true,
    published: true,
    image: null,
    gradient: "from-purple-600 via-pink-600 to-amber-500",
    accentColor: "#a855f7",
    emoji: "🕹️",
    outcome: "Built & Launched",
  },
  {
    id: "2",
    slug: "student-deadline-radar",
    title: "Campus Deadline Radar",
    tagline: "Real-time task & assignment manager for university students",
    shortDescription: "Kanban task manager with urgency scoring algorithms, collaborative group boards, and automated submission reminders.",
    description: "A full-stack collaborative productivity platform designed specifically for university coursework, semester projects, and campus team sprints.",
    problem: "Students juggle 6+ subjects, group assignments, and hackathons across scattered WhatsApp groups and forgotten Google Docs.",
    solution: "Engineered a smart deadline radar with dynamic urgency metrics, subject boards, real-time Supabase sync, and clean mobile UI.",
    results: "Pilot tested across 60+ engineering students with a 65% decrease in last-minute submission misses.",
    category: "Full Stack",
    status: "completed",
    tech: ["Next.js", "TypeScript", "Supabase", "PostgreSQL", "Tailwind CSS"],
    keyFeatures: [
      "Urgency scoring algorithm based on submission date",
      "Real-time team collaboration with Supabase RLS",
      "Subject-wise resource and link vault",
      "Interactive calendar & Kanban views",
      "Exportable summary for project mentors",
    ],
    githubUrl: "https://github.com/yourusername/deadline-radar",
    liveUrl: "https://deadline-radar.vercel.app",
    featured: true,
    published: true,
    image: null,
    gradient: "from-blue-600 via-purple-600 to-pink-500",
    accentColor: "#38bdf8",
    emoji: "⏰",
    outcome: "60+ Active Student Users",
  },
  {
    id: "3",
    slug: "campus-gear-marketplace",
    title: "CampusTrade Student Market",
    tagline: "Peer-to-peer campus marketplace for verified students",
    shortDescription: "Hyperlocal marketplace for buying, selling, and renting lab kits, textbooks, and electronics within college campuses.",
    description: "A secure, college-email verified peer-to-peer marketplace that connects students within the same campus for instant cash or UPI trades.",
    problem: "Students buy expensive lab equipment and textbooks each semester only to have them gather dust, with no safe campus resale platform.",
    solution: "Created an institution-gated web app with .edu / college email verification, in-app chat, and seller trust badges.",
    results: "Facilitated over ₹3,20,000 in peer-to-peer student transactions with zero scam reports.",
    category: "Student Project",
    status: "completed",
    tech: ["Next.js", "Supabase Auth", "PostgreSQL", "Tailwind CSS", "Cloudinary"],
    keyFeatures: [
      "University email domain verification gate",
      "Real-time buyer-seller instant chat",
      "Listing manager with multi-image uploads",
      "Campus location filter & category search",
      "Student reputation and badge score",
    ],
    githubUrl: "https://github.com/yourusername/campustrade",
    liveUrl: "https://campustrade.vercel.app",
    featured: true,
    published: true,
    image: null,
    gradient: "from-pink-500 via-rose-600 to-purple-600",
    accentColor: "#ec4899",
    emoji: "🛍️",
    outcome: "₹3.2L+ Campus Transactions",
  },
  {
    id: "4",
    slug: "viva-code-companion",
    title: "VivaCode AI Explainer",
    tagline: "AI assistant that prepares students for project viva & defense",
    shortDescription: "Upload your repository to generate customized viva questions, line-by-line code explanations, and architecture flashcards.",
    description: "An AI-powered preparation tool that scans student codebases to generate mock viva defense questions, examiner traps, and conceptual breakdowns.",
    problem: "Students often know what their project does at a high level but panic when asked about specific database triggers or API middleware.",
    solution: "Built an intelligent code parser that generates tailored viva quizzes, examiner question predictions, and simplified cheat sheets.",
    results: "Assisted 120+ students across final semester project evaluations with an average defense grade increase.",
    category: "AI",
    status: "in_progress",
    tech: ["Next.js", "TypeScript", "OpenAI API", "Supabase", "Tailwind CSS"],
    keyFeatures: [
      "Repository / code snippet analysis",
      "Predicted examiner viva questions with answers",
      "Architecture diagram generator",
      "Interactive mock viva simulator",
      "Printable PDF defense summary",
    ],
    githubUrl: "https://github.com/yourusername/vivacode",
    liveUrl: "https://vivacode.vercel.app",
    featured: false,
    published: true,
    image: null,
    gradient: "from-amber-500 via-orange-600 to-purple-600",
    accentColor: "#f59e0b",
    emoji: "🤖",
    outcome: "120+ Viva Students Helped",
  },
  {
    id: "5",
    slug: "saas-launch-kit",
    title: "SuperFast SaaS Launchpad",
    tagline: "High-conversion boilerplate & landing template for student founders",
    shortDescription: "Modern landing and product template with pricing switcher, testimonial carousel, and Supabase auth integrations.",
    description: "A production-tested landing page and frontend foundation designed for builders wanting to validate and launch ideas in under 48 hours.",
    problem: "Builders waste 3 weeks styling buttons and setting up Tailwind instead of validating their core product thesis.",
    solution: "Crafted a modular, conversion-optimized template with pre-built pricing toggles, FAQs, feature grids, and analytics hooks.",
    results: "Used by 15+ student startups and hackathon winners to launch their public waiting lists.",
    category: "Frontend",
    status: "completed",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    keyFeatures: [
      "Dynamic pricing calculator with currency switcher",
      "Interactive FAQ accordion with category filters",
      "High-converting hero section with visual mockups",
      "SEO & social share card automated generators",
      "Dark mode first design system",
    ],
    githubUrl: "https://github.com/yourusername/saas-launch-kit",
    liveUrl: "https://saaskit-demo.vercel.app",
    featured: false,
    published: true,
    image: null,
    gradient: "from-emerald-500 via-teal-600 to-purple-600",
    accentColor: "#10b981",
    emoji: "⚡",
    outcome: "15+ Startups Launched",
  },
];

// Section 7: "From idea → internet"
export const PROCESS_STEPS = [
  {
    number: "01",
    stepTitle: "Tell us the idea.",
    description: "You tell us what you're trying to build — whether it's a rough sketch on a napkin, a Notes app document, or an urgent assignment due next week.",
    outcome: "Scope breakdown & clear estimate",
    emoji: "💡",
  },
  {
    number: "02",
    stepTitle: "Figure out what actually needs to be built.",
    description: "We define the core features, database schema, user flows, and deadlines so you know exactly what you're getting before any coding begins.",
    outcome: "Architecture plan & roadmap",
    emoji: "📝",
  },
  {
    number: "03",
    stepTitle: "Build it.",
    description: "Development begins in focused sprints using Next.js, TypeScript, and Supabase. You get live preview links to test features as they are created.",
    outcome: "Live preview staging links",
    emoji: "🛠️",
  },
  {
    number: "04",
    stepTitle: "Test everything.",
    description: "We test edge cases, mobile responsiveness, auth security rules, and error states until everything runs buttery smooth with zero glitches.",
    outcome: "Bulletproof testing & polish",
    emoji: "🧪",
  },
  {
    number: "05",
    stepTitle: "Ship it.",
    description: "Deployment to Vercel and Supabase Cloud, custom domain setup, full repository handover, documentation, and a 1-on-1 walkthrough.",
    outcome: "Live product + full code ownership",
    emoji: "🚀",
  },
];

// Section 8: "How much is this going to cost?"
export const PRICING_CATEGORIES = [
  {
    id: "website",
    title: "Just need a website?",
    subtitle: "For personal brands, landing pages, and portfolios that need to look fire.",
    tag: "Fast Turnaround",
    description: "Custom responsive site built with Next.js, sub-second page speeds, contact form, SEO setup, and Vercel deployment.",
    ctaText: "Let's discuss →",
    color: "#38bdf8",
  },
  {
    id: "capstone",
    title: "Have a bigger idea?",
    subtitle: "For student capstones, academic projects, and web apps with authentication.",
    tag: "Most Popular",
    description: "Complete full-stack app with Supabase database, auth, full PDF/Word documentation, presentation slides, and 1-on-1 viva prep walkthrough.",
    ctaText: "Let's discuss →",
    color: "#a855f7",
  },
  {
    id: "startup",
    title: "Building something serious?",
    subtitle: "For startups, campus founders, and creators launching a real production MVP.",
    tag: "Full MVP",
    description: "Production-ready web application with admin controls, payment integration, database RLS security, and post-launch support.",
    ctaText: "Let's discuss →",
    color: "#ec4899",
  },
];

// Section 9: Authentic Wall of Fame
export const TESTIMONIALS = [
  {
    name: "Karthik R.",
    role: "Final Year CS Student",
    institution: "Anna University",
    content: "CodeMachan saved my final year project. 8 days before our review, our team had broken code. They restructured everything into Next.js + Supabase, gave us clean docs, and walked me through every line so I nailed the viva questions!",
    project: "Campus Task Radar",
    avatar: "🎓",
  },
  {
    name: "Ananya M.",
    role: "Campus Founder",
    institution: "Tech Club Lead",
    content: "Needed an event registration portal built over a weekend. CodeMachan delivered a super sleek dark mode site with QR verification. The whole campus loved it!",
    project: "CampusTrade MVP",
    avatar: "⚡",
  },
  {
    name: "Siddharth V.",
    role: "Junior Web Developer",
    institution: "Freelance Client",
    content: "My portfolio was getting zero recruiter callbacks. CodeMachan redesigned it with case studies and personality. Landed 3 interview calls within two weeks of updating my link.",
    project: "Developer Portfolio",
    avatar: "💼",
  },
];

export const FAQS = [
  {
    question: "How fast can you build my project?",
    answer: "Simple websites take 3–5 days. Student projects with documentation take 5–8 days. Full-stack MVPs take 10–18 days. Urgent submission timelines are also available upon request.",
  },
  {
    question: "Will I understand the code for my viva or presentation?",
    answer: "100%. We write clean, commented code, provide architecture diagrams, and schedule a 1-on-1 video call where we walk you through the logic, database relationships, and expected examiner questions.",
  },
  {
    question: "How do we get started?",
    answer: "Fill out the inquiry form below or message us with a brief summary of what you want to build. We'll get back to you within 12 hours with a clear roadmap!",
  },
];

export const CATEGORIES = [
  { id: "all", label: "All Built Projects", emoji: "✨" },
  { id: "Full Stack", label: "Full-Stack Apps", emoji: "📱" },
  { id: "Student Project", label: "Student Projects", emoji: "🎓" },
  { id: "Frontend", label: "Frontend & UI", emoji: "🎨" },
  { id: "AI", label: "AI Experiments", emoji: "🤖" },
];

export const SOCIAL_LINKS = [
  { platform: "GitHub", url: "https://github.com/yourusername", icon: "Github" },
  { platform: "LinkedIn", url: "https://linkedin.com/in/yourusername", icon: "Linkedin" },
  { platform: "Twitter", url: "https://twitter.com/codemachan", icon: "Twitter" },
  { platform: "Instagram", url: "https://instagram.com/codemachan", icon: "Instagram" },
  { platform: "Email", url: "mailto:codemachan@gmail.com", icon: "Mail" },
];

export const SKILLS = [
  { id: "1", name: "Next.js", category: "frontend", proficiency: 92, color: "#ffffff" },
  { id: "2", name: "React", category: "frontend", proficiency: 90, color: "#61DAFB" },
  { id: "3", name: "TypeScript", category: "frontend", proficiency: 88, color: "#3178C6" },
  { id: "4", name: "Tailwind CSS", category: "frontend", proficiency: 95, color: "#06B6D4" },
  { id: "5", name: "Supabase", category: "backend", proficiency: 90, color: "#3ECF8E" },
  { id: "6", name: "PostgreSQL", category: "backend", proficiency: 85, color: "#4169E1" },
];
